using System.Collections.Generic;
using UnityEngine;

namespace FairyGUI
{
    /// <summary>
    ///     Base class for all kind of fonts.
    /// </summary>
    public class BaseFont
    {
        protected const float SupScale = 0.58f;
        protected const float SupOffset = 0.33f;

        protected internal static bool textRebuildFlag;

        /// <summary>
        ///     Can this font be tinted? Will be true for dynamic font and fonts generated by BMFont.
        /// </summary>
        public bool canTint;

        /// <summary>
        ///     If true, it will use extra vertices to enhance bold effect
        /// </summary>
        public bool customBold;

        /// <summary>
        ///     If true, it will use extra vertices to enhance bold effect ONLY when it is in italic style.
        /// </summary>
        public bool customBoldAndItalic;

        /// <summary>
        ///     If true, it will use extra vertices(4 direction) to enhance outline effect
        /// </summary>
        public bool customOutline;

        /// <summary>
        ///     Keep text crisp.
        /// </summary>
        public bool keepCrisp;

        /// <summary>
        ///     The texture of this font object.
        /// </summary>
        public NTexture mainTexture;

        /// <summary>
        ///     The name of this font object.
        /// </summary>
        public string name;

        /// <summary>
        ///     The shader for this font object.
        /// </summary>
        public string shader;

        /// <summary>
        /// </summary>
        public int version;

        public virtual void UpdateGraphics(NGraphics graphics)
        {
        }

        public virtual void SetFormat(TextFormat format, float fontSizeScale)
        {
        }

        public virtual void PrepareCharacters(string text)
        {
        }

        public virtual bool GetGlyph(char ch, out float width, out float height, out float baseline)
        {
            width = 0;
            height = 0;
            baseline = 0;
            return false;
        }

        public virtual int DrawGlyph(float x, float y,
            List<Vector3> vertList, List<Vector2> uvList, List<Vector2> uv2List, List<Color32> colList)
        {
            return 0;
        }

        public virtual int DrawLine(float x, float y, float width, int fontSize, int type,
            List<Vector3> vertList, List<Vector2> uvList, List<Vector2> uv2List, List<Color32> colList)
        {
            return 0;
        }

        public virtual bool HasCharacter(char ch)
        {
            return false;
        }

        public virtual int GetLineHeight(int size)
        {
            return 0;
        }

        public virtual void Dispose()
        {
        }
    }
}